In [11]:
import numpy

In [12]:
print("Hello")

Hello


In [13]:
import numpy as np
sample = [1,2,3,4]
type(sample)
sample2 = []
for i in sample:
   sample2.append(i+2)
   print(sample2) 


[3]
[3, 4]
[3, 4, 5]
[3, 4, 5, 6]


In [ ]:
array = np.array(sample)
type (array)
array2 = array+2
print(array2)

[3 4 5 6]


In [21]:
#error_array = np.array([1,2,4],"name")
error_array = np.array([1,2,4])
arrayzero = np.zeros(5)
print(arrayzero)
onesarray = np.ones(5)
print(onesarray)
multiones = np.ones((3,4))
print(multiones)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
array_2d = np.array([[1,2],[3,4],[5,6]])
print(array_2d)
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d.size)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6
