In [1]:
import numpy as np



In [3]:
array = np.random.randint(0,100, size = 10)
print(array)
array2 = array[array%2==0]
print(array2)
array3 = array[array%3==0]
print(array3)
array4 = array[array>30]
print(array4)

[25 89 34 61 90  7  5 49 42 72]
[34 90 42 72]
[90 42 72]
[89 34 61 90 49 42 72]
