In [1]:
import numpy

In [2]:
print("Hello")

Hello


In [3]:
import numpy as np
sample = [1,2,3,4]
type(sample)
sample2 = []
for i in sample:
   sample2.append(i+2)
   print(sample2) 


[3]
[3, 4]
[3, 4, 5]
[3, 4, 5, 6]


In [ ]:
array = np.array(sample)
type (array)
array2 = array+2
print(array2)


[3 4 5 6]


In [5]:
#error_array = np.array([1,2,4],"name")
error_array = np.array([1,2,4])
arrayzero = np.zeros(5)
print(arrayzero)
onesarray = np.ones(5)
print(onesarray)
multiones = np.ones((3,4))
print(multiones)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
array_2d = np.array([[1,2],[3,4],[5,6]])
print(array_2d)
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d.size)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6


In [13]:
import numpy as np
lst = [1,2,3,4,5]
arr = np.array(lst)
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.size)
float_array = np.array([1,2,3,4,5],dtype='float')
print(float_array)
zeros_array = np.zeros(5)
print(zeros_array)
ones_array = np.zeros(5)
print(ones_array)
multiones = np.ones((3,4))
print(multiones)
float_array = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype='float')
print(float_array)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)
10
[1. 2. 3. 4. 5.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
