In [2]:
import numpy as np
array = np.arange(1,101)
array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
array = np.arange(5,16,2)
array

array([ 5,  7,  9, 11, 13, 15])

In [6]:
array = np.arange(2,101,2)
array
array2 = np.random.permutation(array)
print(array2)

[ 68  50  62  52  14  74  72  80  18  76  90  22  84  26  24  38   8  82
  34  98  86  58  10  70  42   6  46  60  78  54   4  66  16  88  20  32
  36  40  94  64  44  92   2 100  30  28  96  56  12  48]


In [7]:
array = np.random.randint(0,100, size = 10)
print(array)

[80 98 59 22 57 85 67 95 56 12]


In [10]:
array = np.random.rand(2,3)
print(array)

[[0.25924506 0.34276817 0.58561035]
 [0.07242928 0.37011418 0.53705923]]


In [12]:
array = np.arange(2,101,2)
array
array2 = np.random.permutation(array).reshape(5,10)
print(array2)
array3 = np.sort(array2)
print(array3)

[[ 20  60  44  64  10  30   6  98  90  16]
 [ 22  36  24  78  18  88  14  80   4  40]
 [ 62  68  12  66  50  74  72  28  56 100]
 [ 52  82  32  96  48  58  76  94  54  86]
 [ 70   2  84  26  42   8  92  34  38  46]]
[[  6  10  16  20  30  44  60  64  90  98]
 [  4  14  18  22  24  36  40  78  80  88]
 [ 12  28  50  56  62  66  68  72  74 100]
 [ 32  48  52  54  58  76  82  86  94  96]
 [  2   8  26  34  38  42  46  70  84  92]]


In [20]:
linear_array = np.array([1,2,3,4,5,6,7,8])
print(linear_array[3:6])
multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(multi_array[0:2,0:2])


[4 5 6]
[[1 2]
 [4 5]]
